<a href="https://colab.research.google.com/github/Asma-malica/ML/blob/main/ML_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy


#Numpy is the core library for scientific computing in python



In [ ]:
#Numpy is the core library for scientific computing in python

import numpy as np

In [ ]:
ls = [10,20,30]
print(ls)

[10, 20, 30]


In [ ]:
#list
a = [10,20]
print(a)
a.append([30,40])
print(a)
a.extend([50,60])
print(a)
a.insert(5,70)
print(a)

[10, 20]
[10, 20, [30, 40]]
[10, 20, [30, 40], 50, 60]
[10, 20, [30, 40], 50, 60, 70]


In [ ]:
#tuple
a = (10,20,30,20)
print(a)
print(a.index(10))
print(a.count(20))




(10, 20, 30, 20)
0
2


In [ ]:
#dict
a = {10,20,30}
print(a)

{10, 20, 30}


numpy is a grid of an array


In [ ]:
a = np.array([1,2,3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [ ]:
a = np.arange(3,15)
print(a)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
a = np.array([1,2,3],dtype  = np.float64)
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)


[1. 2. 3.]
[[1 2 3]
 [4 5 6]]


In [ ]:
print(type(a))
print(a.shape)
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)


n determines the rank of the array \n


ndimensions






In [ ]:
print(np.ones(2))
print(np.zeros(2))
print(np.random.random(2))

[1. 1.]
[0. 0.]
[0.72466032 0.58728478]


In [ ]:
print(np.ones((2,2,3)))
print(np.zeros((2,2)))
print(np.random.random((2,2)))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[0. 0.]
 [0. 0.]]
[[0.72318445 0.38088554]
 [0.42810434 0.82585803]]


In [ ]:
# a = np.full((2,2))
# print(a)
print(np.eye(3)) #eye --? identity matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.arange(10,50,5))

[10 15 20 25 30 35 40 45]


In [ ]:
print(np.linspace(0.,1.,num = 5)) #num --> keyword #linspace -->splitting the value into 5(num) times

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
 print(np.array([1,2,3]))

[1 2 3]


In [ ]:
#indexing
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,1])
print(a[0:2,0])  # 0 -->row 2-->  0-->
print(a[0:2,1])
print(a[1:3])
print(a[1,2])
print(a[1:2,2])


[[1 2 3]
 [4 5 6]]
2
[1 4]
[2 5]
[[4 5 6]]
6
[6]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.shape)
b = a[:2,1:3]
print(b)
c = a[1:3,2:4]
print(c)


(3, 4)
[[2 3]
 [6 7]]
[[ 7  8]
 [11 12]]


slice of an array is a view into the same data

In [ ]:
print(a[0,1])

2


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
r1 = a[1,:]
print(r1,r1.shape)
r2 = a[1:2, :]
print(r2,r2.shape)
r3 = a[[1],:]
print(r3,r3.shape)
r4 = a[[2],0:4]
print(r4)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)
[[ 9 10 11 12]]


In [ ]:
c1 = a[:,1]
print(c1)
c2 = a[:,1:2]
print(c2)

[ 2  6 10]
[[ 2]
 [ 6]
 [10]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
b = np.array([0,2,0,3])  #0,2,0,1 --> index ,, np.arange() it retrieves the element of that particular index
print(a[np.arange(4),b])
print(a[np.arange(4),b]+10)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  7  9 16]
[11 17 19 26]


boolean array indexing


In [ ]:
print(a>2)
print(a[a>2])
print(a[a<=2])

[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[1 2]


print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a>=a[np.argamax(a)])[0])

In [ ]:
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a>=a[np.argmax(a)])[0])

5
0
[0 1 2 3 4 5]
[5 4 3 2 1 0]
[4 5]
[5]


In [ ]:
a = [1,2,3]
a = np.append(a,[5,6,7])
print(a)

[1 2 3 5 6 7]


In [ ]:
a = np.delete(a,[2,3])
print(a)


[1 2 6 7]


In [ ]:
a = np.array([[1,2],[3,4]])
print(a)
a = np.append(a,[[8,9]])

print(a)

[[1 2]
 [3 4]]
[1 2 3 4 8 9]


In [ ]:
a = np.array([[7,5,1],[5,2,4]])
a = np.sort(a,axis = 1,kind = "quicksort")
print(a)
a = np.sort(a,axis = 1,kind = "heapsort")
print(a)
a = np.sort(a,axis = 1,kind = "mergesort")
print(a)
print(np.sum(a))

[[1 5 7]
 [2 4 5]]
[[1 5 7]
 [2 4 5]]
[[1 5 7]
 [2 4 5]]
24


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.sum(a+b))
print(np.sqrt(a))
print(np.add(a,b))
print(a.dot(b))  # dot ,, @ ,, --> multiplication
print(a@b)
print(np.min(a))
print(np.max(a))



36
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
1
4


In [ ]:
a = np.array([[1],[2],[3]])
c = a.squeeze()  # converts [1],[2],[3] --> [1,2,3] removes unwanted brackets
print(c)
print(a.reshape(-1,1))

[1 2 3]
[[1]
 [2]
 [3]]


In [ ]:
#broadcasting
print(np.array([1,2,3]) + np.array([4,5,6]) )
print(np.array([[1,2,3],[4,5,6]] + np.array([10,20,30])))

[5 7 9]
[[11 22 33]
 [14 25 36]]


In [ ]:
a = np.array([[1,2],[3,4]])
print(a.reshape(1,4))


[[1 2 3 4]]


In [ ]:
# a = np.array([[1,2,3],[4,5,6]])
# print(np.reshape(2,3))

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.reshape(a, (2, 3))
print(b)

[[1 2 3]
 [4 5 6]]
